name:                shitt
version:             0.1.0.0
github:              "githubuser/shitt"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/shitt#readme>
dependencies:
- base >= 4.7 && < 5
- transformers 
- containers 
- vector 
- exception-transformers
- megaparsec
- mtl
- matrix

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

- -Wno-name-shadowing
- -Wno-missing-signatures
- -Wno-unused-do-bind
- -Wno-missing-export-lists
- -Wno-unused-matches
- -Wno-unrecognised-pragmas

library:
  source-dirs: src

executables:
  shitt-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shitt

tests:
  shitt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shitt

default-extensions:
- DerivingVia
- DeriveAnyClass
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- FlexibleContexts
- GeneralizedNewtypeDeriving
- LambdaCase
- OverloadedStrings
- PatternSynonyms
- StandaloneDeriving
- TupleSections
- ViewPatterns
- OverloadedRecordDot
- Strict
- MultiParamTypeClasses
- BlockArguments
- NondecreasingIndentation
- FunctionalDependencies
- FlexibleInstances